# Site settings
title: Ms_AxD
description: Hacking Study
author: ms-axd
email: psrk3421@naver.com
baseurl: ""
url: "https://ms-axd.github.io"
repository: "ms-axd/ms-axd.github.io"

github: [metadata]

markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10
paginate_path: "/blog/page:num/"

collections:
  categories:
    output: true
    permalink: /categories/:name/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      permalink: /blog/:year/:month/:day/:slug/

show_drafts: false
timezone: Asia/Seoul

nav_links:
  - title: Home
    url: /
    icon: H
  - title: Categories
    url: /categories/
    icon: C
  - title: Tags
    url: /tags/
    icon: T
  - title: Archives
    url: /archives/
    icon: A
  - title: About
    url: /about.html
    icon: I

category_list:
  - Bug bounty
  - CTF/Wargame
  - 개발
  - 자격증/공모전
  - 논문/컨퍼런스
  - 블로그/기술문서